export const categories = [
    { category: 'Icons', icon: 'https://i.ibb.co.com/BZ1V2Gh/Icons.png' },
    { category: 'Arctic', icon: 'https://i.ibb.co.com/RDr7g0r/Arctic.png' },
    { category: 'Barns', icon: 'https://i.ibb.co.com/bKB3Jq3/barns.png' },
    { category: 'Cabins', icon: 'https://i.ibb.co.com/6mQN5B3/cabins.png' },
    { category: 'Camping', icon: 'https://i.ibb.co.com/jZKmCbf/camping.png' },
    { category: 'Castles', icon: 'https://i.ibb.co.com/M19NdFw/castles.png' },
    { category: 'Cave', icon: 'https://i.ibb.co.com/sv7mTdV/cave.png' },
    { category: 'Countryside', icon: 'https://i.ibb.co.com/F47PN3Q/countryside.png' },
    { category: 'Earth Homes', icon: 'https://i.ibb.co.com/dpyJCD5/earth-homes.png' },
    { category: 'Farms', icon: 'https://i.ibb.co.com/74nrcpt/farms.png' },
    { category: 'Golf', icon: 'https://i.ibb.co.com/xDfqfc5/golf.png' },
    { category: 'Houseboats', icon: 'https://i.ibb.co.com/N6x3zS4/houseboats.png' },
    { category: 'Islands', icon: 'https://i.ibb.co.com/JzL0tk7/Islands.png' },
    { category: 'Lake', icon: 'https://i.ibb.co.com/WW9b281/lake.png' },
    { category: 'Lakefront', icon: 'https://i.ibb.co.com/Kr9W2f0/lakefront.png' },
    { category: 'New', icon: 'https://i.ibb.co.com/k0Xyyd6/new.png' },
    { category: 'Off the Grid', icon: 'https://i.ibb.co.com/5nnxY5S/offthegrid.png' },
    { category: 'OMG', icon: 'https://i.ibb.co.com/FhDZnc0/omg.png' },
    { category: 'Surfing', icon: 'https://i.ibb.co.com/S7QBRxr/surfing.png' },
    { category: 'Top Cities', icon: 'https://i.ibb.co.com/KmsPS8v/topcities.png' },
    { category: 'Tropical', icon: 'https://i.ibb.co.com/tM56mHH/tropical.png' },
    { category: 'Trulli', icon: 'https://i.ibb.co.com/8gnv4nR/trulli.png' },
    { category: 'Windmills', icon: 'https://i.ibb.co.com/mBZWXYt/windmills.png' }
];
